ignore:
  - 'node_modules/'
  - 'src/base/utils/document-component.tsx'
  - 'src/base/utils/story-with-state.js'
  - 'src/base/test-polyfill.js'
  - 'src/index.tsx.js'
  - 'src/setupTests.js'
  - 'src/rmwc/**/*'
  - 'src/**/*.story.*'
  - 'src/**/*.spec.*'
