ignore:
  - "node_modules/"
  - "src/**/*.flow.js"
  - "src/**/*.story.js"
  - "src/index.js"
  - "src/setupTests.js"
  - "src/drawer/polyfill.js"
  - "src/rmwc/**/*",
  - "src/base/utils/document-component.js"
  - "src/base/utils/story-with-state.js"
  - "src/base/testPolyfill.js"
  - "src/icon/defs.js"